language: node_js

services:
  - postgresql
  - redis-server

before_script:
  - psql -c "CREATE DATABASE silverback_test;" -U postgres
  - psql -c "CREATE USER developer WITH PASSWORD 'developer';" -U postgres
  - psql -U postgres silverback_test -c 'create extension if not exists "uuid-ossp";'

node_js:
  - "node"
  - "8"
  - "10"

sudo: false

script:
  - npm run lint
  - npm run build
  - npm run test:coverage
  - npm audit

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
