language: node_js

services:
  - postgresql

env:
  global:
  - NODE_ENV=test
  - PGPORT=5432
  - PGHOST=localhost

before_script:
  - psql -c "CREATE DATABASE silverback_test;" -U postgres
  - psql -c "CREATE USER developer WITH PASSWORD 'developer';" -U postgres
  - psql -U postgres silverback_test -c 'create extension "uuid-ossp";'

node_js:
  - "8"

sudo: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true
  directories:
    - "node_modules"

script:
  - yarn test
