image: node:8

definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: silverback_test
        POSTGRES_USER: developer
        POSTGRES_PASSWORD: developer
pipelines:
  branches:
    develop:
      - step:
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
            - export PATH=$HOME/.yarn/bin:$PATH
            - yarn cache dir
            - yarn
            - yarn global add ts-node typescript typings
            - yarn lint
            - yarn test
          services:
            - postgres
    master:
      - step:
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
            - export PATH=$HOME/.yarn/bin:$PATH
            - yarn cache dir
            - yarn
            - yarn global add ts-node typescript typings
            - yarn lint
            - yarn test
          services:
            - postgres
