image: node:8
clone:
  depth: full
definitions:
  services:
    postgres:
      image: sameersbn/postgresql:latest
      environment:
        DB_USER: developer
        DB_PASS: developer
        DB_NAME: silverback_test
        DB_EXTENSION: '"uuid-ossp"'
pipelines:
  branches:
    develop:
      - step:
          caches:
            - node
          script:
            - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
            - export PATH=$HOME/.yarn/bin:$PATH
            - yarn cache dir
            - yarn
            - yarn lint
            - yarn test
          services:
            - postgres
      - step:
          name: Deploy to development
          deployment: test
          trigger: manual
          script:
            - yarn global add heroku-cli
            - heroku --version
            - heroku login
  default:
    - step:
        caches:
          - node
        script:
          - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
          - export PATH=$HOME/.yarn/bin:$PATH
          - yarn cache dir
          - yarn
          - yarn lint
          - yarn test
        services:
          - postgres
